export const EMAILJS_CONFIG = {
  SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || '',
  TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || '',
  TEMPLATE_ID_INKOOP: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_INKOOP || '',
  TEMPLATE_ID_ONDERHOUD: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_ONDERHOUD || '',
  PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || '',
};
